-- MySQL Script generated by MySQL Workbench
-- Tue Jul 31 00:13:07 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema myblog
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `myblog` ;

-- -----------------------------------------------------
-- Schema myblog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myblog` DEFAULT CHARACTER SET utf8 ;
USE `myblog` ;

-- -----------------------------------------------------
-- Table `myblog`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myblog`.`Category` ;

CREATE TABLE IF NOT EXISTS `myblog`.`Category` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '编号',
  `name` VARCHAR(45) NOT NULL COMMENT '类别标题',
  `total` INT(11) NOT NULL DEFAULT '0' COMMENT '该类别的文章总数',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8
COMMENT = '文章类别表';


-- -----------------------------------------------------
-- Table `myblog`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myblog`.`User` ;

CREATE TABLE IF NOT EXISTS `myblog`.`User` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '博主编号',
  `account` VARCHAR(20) NULL DEFAULT NULL COMMENT '账号',
  `name` VARCHAR(20) NOT NULL COMMENT '姓名',
  `password` VARCHAR(100) NULL DEFAULT NULL COMMENT '密码',
  `salt` VARCHAR(50) NULL DEFAULT NULL,
  `resume_url` VARCHAR(100) NULL DEFAULT NULL COMMENT '简历链接',
  `secondary_password` VARCHAR(100) NULL DEFAULT NULL COMMENT '二级密码',
  `address` VARCHAR(30) NULL DEFAULT NULL COMMENT '地址id',
  `wechat` VARCHAR(40) NULL DEFAULT NULL COMMENT '微信id',
  `github_url` VARCHAR(40) NULL DEFAULT NULL COMMENT 'github',
  `phone` INT(15) NULL DEFAULT NULL COMMENT '手机号',
  `avatar_url` VARCHAR(100) NULL DEFAULT NULL COMMENT '头像src',
  `github_id` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Github id - 基于github第三方登录的游客信息的唯一标志',
  `role` INT(11) NOT NULL DEFAULT '0' COMMENT '0 - 普通用户\n1 - 博主',
  `email` VARCHAR(30) NULL DEFAULT '' COMMENT 'email',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `account` (`account` ASC),
  UNIQUE INDEX `github_id_UNIQUE` (`github_id` ASC),
  UNIQUE INDEX `github_UNIQUE` (`github_url` ASC),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 43
DEFAULT CHARACTER SET = utf8
COMMENT = '实体表-用户表';


-- -----------------------------------------------------
-- Table `myblog`.`Article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myblog`.`Article` ;

CREATE TABLE IF NOT EXISTS `myblog`.`Article` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '编号',
  `title` VARCHAR(50) NOT NULL COMMENT '标题',
  `content` LONGTEXT NULL DEFAULT NULL COMMENT '内容 - 长度限制：3000',
  `summary` VARCHAR(200) NOT NULL COMMENT '文章简介',
  `read_num` INT(10) NOT NULL DEFAULT '0' COMMENT '浏览次数',
  `prev_id` CHAR(10) NULL DEFAULT NULL COMMENT '上一篇文章的id',
  `next_id` CHAR(10) NULL DEFAULT NULL COMMENT '下一篇文章的id	',
  `pubtime` VARCHAR(10) NULL DEFAULT NULL COMMENT '写作开始时间',
  `cover_url` VARCHAR(200) NULL DEFAULT NULL COMMENT '封面uri',
  `category_id` INT(10) NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `lastId` USING BTREE (`prev_id` ASC),
  INDEX `nextId` USING BTREE (`next_id` ASC),
  INDEX `fk_Article_Category1_idx` (`category_id` ASC),
  INDEX `fk_Article_User1_idx` (`user_id` ASC),
  INDEX `title` USING BTREE (`title` ASC),
  CONSTRAINT `fk_Article_Category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `myblog`.`Category` (`id`),
  CONSTRAINT `fk_Article_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `myblog`.`User` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 86
DEFAULT CHARACTER SET = utf8
COMMENT = '实体表-文章表';


-- -----------------------------------------------------
-- Table `myblog`.`Comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myblog`.`Comment` ;

CREATE TABLE IF NOT EXISTS `myblog`.`Comment` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '编号',
  `time` VARCHAR(45) NOT NULL COMMENT '评论时间',
  `content` VARCHAR(300) NOT NULL COMMENT '评论内容',
  `article_id` INT(10) UNSIGNED NOT NULL,
  `to_uid` INT(10) UNSIGNED NULL DEFAULT '0' COMMENT '评论目标人id',
  `from_uid` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `from_uid`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Comment_Article1_idx` (`article_id` ASC),
  INDEX `fk_Comment_User2_idx` (`to_uid` ASC),
  INDEX `fk_Comment_User1_idx` (`from_uid` ASC),
  CONSTRAINT `fk_Comment_Article10`
    FOREIGN KEY (`article_id`)
    REFERENCES `myblog`.`Article` (`id`),
  CONSTRAINT `fk_Comment_User1`
    FOREIGN KEY (`from_uid`)
    REFERENCES `myblog`.`User` (`id`),
  CONSTRAINT `fk_Comment_User2`
    FOREIGN KEY (`to_uid`)
    REFERENCES `myblog`.`User` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '关系表-留言表';


-- -----------------------------------------------------
-- Table `myblog`.`Liked`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myblog`.`Liked` ;

CREATE TABLE IF NOT EXISTS `myblog`.`Liked` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `type` INT(11) NOT NULL COMMENT '0 - 博文点赞\n1 - 评论点赞\n2 - 回复点赞\n3 - 作品点赞',
  `status` INT(11) NOT NULL COMMENT '0 - 取点赞\n1 - 有点赞',
  `article_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '文章id',
  `comment_id` INT(10) NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Like_Article1_idx` (`article_id` ASC),
  INDEX `fk_Like_Comment1_idx` (`comment_id` ASC),
  INDEX `fk_Like_User1_idx` (`user_id` ASC),
  CONSTRAINT `fk_Like_Article1`
    FOREIGN KEY (`article_id`)
    REFERENCES `myblog`.`Article` (`id`),
  CONSTRAINT `fk_Like_Comment1`
    FOREIGN KEY (`comment_id`)
    REFERENCES `myblog`.`Comment` (`id`),
  CONSTRAINT `fk_Like_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `myblog`.`User` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COMMENT = '关系表-点赞表';


-- -----------------------------------------------------
-- Table `myblog`.`Street`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myblog`.`Street` ;

CREATE TABLE IF NOT EXISTS `myblog`.`Street` (
  `text` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL COMMENT '街道名',
  `id` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL COMMENT '街道id')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '实体表-街道表';


-- -----------------------------------------------------
-- Table `myblog`.`Works`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myblog`.`Works` ;

CREATE TABLE IF NOT EXISTS `myblog`.`Works` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '编号',
  `title` VARCHAR(45) NOT NULL DEFAULT '作品' COMMENT '作品标题',
  `pubtime` VARCHAR(45) NULL DEFAULT NULL COMMENT '出品时间',
  `url` VARCHAR(45) NULL DEFAULT NULL COMMENT '查看地址',
  `github_url` VARCHAR(45) NULL DEFAULT NULL COMMENT 'github源码地址',
  `cover` VARCHAR(45) NULL DEFAULT NULL COMMENT '封面地址',
  `user_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Works_User1_idx` (`user_id` ASC),
  CONSTRAINT `fk_Works_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `myblog`.`User` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '实体表-作品表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
